// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0jhSkZ5qPT41IN3in5SL-cogpdvq15Q',
    appId: '1:671031115878:web:5bc1aab25f9d98db3aada7',
    messagingSenderId: '671031115878',
    projectId: 'thefarmer',
    authDomain: 'thefarmer-69c74.firebaseapp.com',
    storageBucket: 'thefarmer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmHX9r_OR8dImQqCw3tV9l_RBfuxSOAA',
    appId: '1:671031115878:android:4b9e42a5e7f213b33aada7',
    messagingSenderId: '671031115878',
    projectId: 'thefarmer',
    storageBucket: 'thefarmer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEpdtt9ZbpTXpk1lUlvkRV4zz5Yx5gXA',
    appId: '1:671031115878:ios:bfc0d4f9b2f9c9743aada7',
    messagingSenderId: '671031115878',
    projectId: 'thefarmer',
    storageBucket: 'thefarmer.appspot.com',
    androidClientId: '671031115878-r3tdon753mu1b6on8sr5nv6u3ihanabe.apps.googleusercontent.com',
    iosClientId: '671031115878-6i8btuj3dl29qi5ie6kfb98rbqehi1ct.apps.googleusercontent.com',
    iosBundleId: 'com.zubaidalabs.farmer',
  );
}
